### ISSUE TITLE
Dagger 2.x and retrofit 2.x support

### ISSUE THREAD

**Issue by Zenedith** [jacek-marchwicki/rx-java-extensions#84]
Are you planning to add support for Dagger 2.x and retrofit 2.x ?

**Comment by jacek-marchwicki** [comment]
Actually we use in all our projects Dagger 2. And you can use it with this library. I just didnt want to use it in example so example will be easy to understand for non-dagger users.
But definetlly use dependency injection (look on FakeDagger.class)

Also there is no problem to use retrofit2. You just need change imports and initalization a little bit - but this concern only example. Library is also used in projects with retrofit2.
